name: Deploy ADF ARM Template

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy ADF Template
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: resource-grp-test
        template: ./ARMTemplateForFactory/ARMTemplateForFactory.json
        parameters: ./ARMTemplateForFactory/ARMTemplateParametersForFactory.json
        deploymentName: adf-deploy-${{ github.run_number }}
